import { useState, useCallback, useRef } from 'react';

export type SDStatus = 'idle' | 'loading-model' | 'generating' | 'success' | 'error';

export function useSD() {
  const [status, setStatus] = useState<SDStatus>('idle');
  const [progress, setProgress] = useState<string>('');
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [error, setError] = useState<string>('');
  const pipelineRef = useRef<any>(null);

  // Clean up existing generated image URL
  const clearImage = useCallback(() => {
    if (imageUrl) {
      URL.revokeObjectURL(imageUrl);
      setImageUrl(null);
    }
  }, [imageUrl]);

  const generateCloud = useCallback(async (prompt: string, hfToken?: string) => {
    setStatus('generating');
    setProgress('Sending prompt to Hugging Face Inference API…');
    setError('');

    try {
      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
      };
      if (hfToken && hfToken.trim()) {
        headers['Authorization'] = `Bearer ${hfToken.trim()}`;
      }

      // We use FLUX.1-schnell as default because it produces amazing quality in 1-4 steps
      const model = 'black-forest-labs/FLUX.1-schnell';
      const response = await fetch(
        `https://api-inference.huggingface.co/models/${model}`,
        {
          method: 'POST',
          headers,
          body: JSON.stringify({ inputs: prompt }),
        }
      );

      if (!response.ok) {
        const errText = await response.text();
        let errMsg = 'Failed to generate image.';
        try {
          const errObj = JSON.parse(errText);
          errMsg = errObj.error || errMsg;
        } catch {
          if (errText.includes('currently loading')) {
            errMsg = 'Model is currently loading on Hugging Face. Please try again in a few seconds.';
          }
        }
        throw new Error(errMsg);
      }

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      setImageUrl(url);
      setStatus('success');
      setProgress('');
    } catch (err: any) {
      console.error('Cloud generation error:', err);
      setError(err instanceof Error ? err.message : 'An error occurred during image generation.');
      setStatus('error');
    }
  }, []);

  const generateLocal = useCallback(async (prompt: string, steps: number = 20) => {
    setStatus('loading-model');
    setProgress('Loading Stable Diffusion ONNX model into GPU memory (~2.7GB, please wait)…');
    setError('');

    try {
      // Lazy load diffusers.js to keep initial bundle size small and avoid loading if not used
      const { DiffusionPipeline } = await import('@aislamov/diffusers.js');

      if (!pipelineRef.current) {
        pipelineRef.current = await DiffusionPipeline.fromPretrained(
          'aislamov/stable-diffusion-2-1-base-onnx'
        );
      }

      setStatus('generating');
      setProgress('Generating image client-side via WebGPU…');

      const images = await pipelineRef.current.run({
        prompt,
        numInferenceSteps: steps,
      });

      if (!images || images.length === 0) {
        throw new Error('No image was generated by local pipeline.');
      }

      setProgress('Converting image tensor data…');
      const canvas = document.createElement('canvas');
      canvas.width = 512;
      canvas.height = 512;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('Could not create 2D canvas context.');

      const data = await images[0].toImageData({ tensorLayout: 'NCWH', format: 'RGB' });
      ctx.putImageData(data, 0, 0);

      const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
      if (!blob) throw new Error('Failed to export generated canvas to image Blob.');

      const url = URL.createObjectURL(blob);
      setImageUrl(url);
      setStatus('success');
      setProgress('');
    } catch (err: any) {
      console.error('Local generation error:', err);
      setError(
        err instanceof Error
          ? err.message
          : 'Failed to run local Stable Diffusion. Make sure WebGPU is enabled and your device has sufficient VRAM.'
      );
      setStatus('error');
    }
  }, []);

  // Dispose local model to free up VRAM/RAM
  const disposeModel = useCallback(() => {
    if (pipelineRef.current) {
      // If the pipeline has sessions, we release them if they have a release/dispose method
      try {
        if (pipelineRef.current.unet) pipelineRef.current.unet.dispose();
        if (pipelineRef.current.vae) pipelineRef.current.vae.dispose();
        if (pipelineRef.current.textEncoder) pipelineRef.current.textEncoder.dispose();
      } catch { /* ignore */ }
      pipelineRef.current = null;
      if (status === 'success' || status === 'error') {
        setStatus('idle');
      }
    }
  }, [status]);

  return {
    status,
    progress,
    imageUrl,
    error,
    generateCloud,
    generateLocal,
    clearImage,
    disposeModel,
  };
}
